title:              Andy Kwon
email:
description:        "#AWS #Python #DevOps #Docker #Kubernetes #Serverless"
author:             Andy Kwon
baseurl:            ""
url:                "https://andy-kwon.github.io/"

collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

# Social Profiles
twitter_username:
github_username:    andy-kwon
facebook_username:
instagram_username:  
linkedin_username: andy-kwon1203

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-174897990-1 # out your google-analytics code

highlighter: rouge

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
